=== Mario-Devv/xml-daw-exercises/ejercicioRepaso/ejercicio01/XSD/iva.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="misImportes">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="12" />
            <xs:fractionDigits value="2" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="misPorcentajes">
        <xs:restriction base="xs:decimal">
            <xs:enumeration value="21.00" />
            <xs:enumeration value="10.00" />
            <xs:enumeration value="4.00" />
            <xs:enumeration value="0.00" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="miCif">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][0-9]{8}" />
        </xs:restriction>
    </xs:simpleType>


    <xs:element name="resumenIVA">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="presentacion">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="periodo">
                                <xs:complexType>
                                    <xs:attribute name="desde" type="xs:date" use="required" />
                                    <xs:attribute name="hasta" type="xs:date" use="required" />
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="presentador">
                                <xs:complexType mixed="true">
                                    <xs:attribute name="cif" type="miCif" use="required" />
                                    <xs:attribute name="razon" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="liquidacion">
                                <xs:complexType>
                                    <xs:attribute name="importe" type="misImportes" use="required" />
                                    <xs:attribute name="iban" type="xs:string" />
                                    <xs:attribute name="cargo" type="xs:date" use="required" />
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="observaciones" type="xs:string" minOccurs="0" />
                        </xs:all>
                        <xs:attribute name="fecha" type="xs:date" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="soportado" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="iva" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="porcentaje" type="misPorcentajes" use="required" />
                                    <xs:attribute name="base" type="misImportes" use="required" />
                                    <xs:attribute name="cuota" type="misImportes" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="total" type="xs:double" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="repercutido" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="iva" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="porcentaje" type="misPorcentajes" use="required" />
                                    <xs:attribute name="base" type="xs:double" use="required" />
                                    <xs:attribute name="cuota" type="xs:double" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="total" type="xs:double" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Mario-Devv/xml-daw-exercises/ejercicioRepaso/ejercicio01/XSD/iva.xml
<?xml version="1.0" encoding="UTF-8"?>

<resumenIVA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="iva.xsd">
    <presentacion fecha="2016-01-20">
        <periodo desde="2015-10-01" hasta="2015-12-31" />
        <presentador cif="B12345678" razon="Empre,S.A." />
        <liquidacion importe="750.00" iban="ES1812345678901234567890" cargo="2016-01-30" />
        <observaciones />
    </presentacion>
    <soportado total="2400.00">
        <iva porcentaje="21.00" base="10000.00" cuota="2100.00" />
        <iva porcentaje="10.00" base="3000.00" cuota="300.00" />
    </soportado>
    <repercutido total="2400.00">
        <iva porcentaje="21.00" base="15000.00" cuota="3150.00" />
    </repercutido>
</resumenIVA>
