=== Mario-Devv/xml-daw-exercises/ejercicioRepaso/ejercicio01/DTD/lmsgi04.dtd
<!ELEMENT resumenIVA (presentacion, soportado?, repercutido?)>
<!ELEMENT presentacion (periodo, presentador, liquidacion, observaciones?)>
    <!ELEMENT periodo EMPTY>
    <!ELEMENT presentador EMPTY>
    <!ELEMENT liquidacion EMPTY>
    <!ELEMENT observaciones (#PCDATA)>
        <!ATTLIST presentacion fecha CDATA #REQUIRED>
        <!ATTLIST periodo desde CDATA #REQUIRED>
        <!ATTLIST periodo hasta CDATA #REQUIRED>
        <!ATTLIST presentador cif CDATA #REQUIRED>
        <!ATTLIST presentador razon CDATA #REQUIRED>
        <!ATTLIST liquidacion importe CDATA #REQUIRED>
        <!ATTLIST liquidacion iban CDATA #IMPLIED>
        <!ATTLIST liquidacion cargo CDATA #REQUIRED>
<!ELEMENT soportado (iva+)>
<!ELEMENT repercutido (iva+)>
    <!ELEMENT iva EMPTY>
        <!ATTLIST iva porcentaje CDATA #REQUIRED>
        <!ATTLIST iva base CDATA #REQUIRED>
        <!ATTLIST iva cuota CDATA #REQUIRED>
<!ATTLIST soportado total CDATA #REQUIRED>
<!ATTLIST repercutido total CDATA #REQUIRED>

=== Mario-Devv/xml-daw-exercises/ejercicioRepaso/ejercicio01/DTD/iva.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resumenIVA SYSTEM "lmsgi04.dtd">

<resumenIVA>
    <presentacion fecha="2016-01-20">
        <periodo desde="2015-10-01" hasta="2015-12-31" />
        <presentador cif="B12345678" razon="Empre,S.A." />
        <liquidacion importe="750.00" iban="ES1812345678901234567890" cargo="2016-01-30" />
        <observaciones />
    </presentacion>
    <soportado total="2400.00">
        <iva porcentaje="21.00" base="10000.00" cuota="2100.00" />
        <iva porcentaje="10.00" base="3000.00" cuota="300.00" />
    </soportado>
    <repercutido total="2400.00">
        <iva porcentaje="21.00" base="15000.00" cuota="3150.00" />
    </repercutido>
</resumenIVA>
