<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE libros [
    <!ELEMENT libros (libro+)>
    <!ELEMENT libro (titulo, autor, precio)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
]>


<libros>
    <libro>
        <titulo></titulo>
        <autor></autor>
        <precio></precio>
    </libro>
</libros>