=== Mario-Devv/xml-daw-exercises/ejercicioRepaso/ejercicio02/XSD/gastos.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="myDecimal">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="5" />
            <xs:fractionDigits value="2" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="myCantidad">
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="100" />
            <xs:minInclusive value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="myDNI">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{7,8}[A-Z]" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="gastos_empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="conceptos" minOccurs="1" maxOccurs="unbounded" />
                <xs:element name="empleado" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="gastos_empleado">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="gasto" minOccurs="1" maxOccurs="unbounded"
                                        >
                                            <xs:complexType mixed="true">
                                                <xs:attribute name="cantidad" type="myCantidad"
                                                    use="optional" />
                                                <xs:attribute name="id" type="xs:ID" use="required" />
                                                <xs:attribute name="concepto" type="xs:IDREF"
                                                    use="required" />
                                                <xs:attribute name="precio" type="myDecimal"
                                                    use="required" />
                                                <xs:attribute name="fecha" type="xs:date"
                                                    use="required" />

                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="observaciones" minOccurs="0"
                                type="xs:string" />
                        </xs:all>

                        <xs:attribute name="dni" type="myDNI" use="required" />
                        <xs:attribute name="nombre" type="xs:string" use="required" />
                        <xs:attribute name="departamento" type="xs:string" use="optional" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Mario-Devv/xml-daw-exercises/ejercicioRepaso/ejercicio02/XSD/gastos.xml
<?xml version="1.0" encoding="UTF-8"?>

<gastos_empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./gastos.xsd">
    <conceptos> </conceptos>
    <empleado dni="ES22123456F" nombre="Gregorio Alsina">
        <gastos_empleado>
            <gasto id="G17011201" fecha="2017-01-12" concepto="km" cantidad="105" precio="0.30" />
            <gasto id="G17011202" fecha="2017-01-12" concepto="dc" precio="15" />
            <gasto id="G17011203" fecha="2017-01-12" concepto="ot" precio="12"> Paso a la vuelta por
                la Roda por Miguelitos </gasto>
        </gastos_empleado>
    </empleado>
    <empleado dni="ES77456789K" nombre="Carla Egea" departamento="Marketing">
        <gastos_empleado>
            <gasto id="G17011301" fecha="2017-01-13" concepto="dd" precio="25" />
            <gasto id="G17011302" fecha="2017-01-13" concepto="dc" precio="15"> Invito a cliente a
                comer conmigo, por eso figuran dos comidas en la misma fecha </gasto>
        </gastos_empleado>
        <observaciones>No hay kilometraje porque fue junto a mi residencia</observaciones>
    </empleado>
</gastos_empresa>
